/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialogAction: typeof import('radix-vue')['AlertDialogAction']
    AlertDialogContent: typeof import('radix-vue')['AlertDialogContent']
    AlertDialogDescription: typeof import('radix-vue')['AlertDialogDescription']
    AlertDialogOverlay: typeof import('radix-vue')['AlertDialogOverlay']
    AlertDialogPortal: typeof import('radix-vue')['AlertDialogPortal']
    AlertDialogRoot: typeof import('radix-vue')['AlertDialogRoot']
    AlertDialogTitle: typeof import('radix-vue')['AlertDialogTitle']
    Label: typeof import('radix-vue')['Label']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectContent: typeof import('radix-vue')['SelectContent']
    SelectGroup: typeof import('radix-vue')['SelectGroup']
    SelectItem: typeof import('radix-vue')['SelectItem']
    SelectItemIndicator: typeof import('radix-vue')['SelectItemIndicator']
    SelectItemText: typeof import('radix-vue')['SelectItemText']
    SelectPortal: typeof import('radix-vue')['SelectPortal']
    SelectRoot: typeof import('radix-vue')['SelectRoot']
    SelectScrollDownButton: typeof import('radix-vue')['SelectScrollDownButton']
    SelectScrollUpButton: typeof import('radix-vue')['SelectScrollUpButton']
    SelectTrigger: typeof import('radix-vue')['SelectTrigger']
    SelectValue: typeof import('radix-vue')['SelectValue']
    SelectViewport: typeof import('radix-vue')['SelectViewport']
  }
}
