name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Detect package manager
      id: detect-package-manager
      run: |
        if [ -f "${{ github.workspace }}/yarn.lock" ]; then
          echo "manager=yarn" >> $GITHUB_OUTPUT
          echo "command=install" >> $GITHUB_OUTPUT
          echo "runner=yarn" >> $GITHUB_OUTPUT
          echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
          exit 0
        elif [ -f "${{ github.workspace }}/package.json" ]; then
          echo "manager=npm" >> $GITHUB_OUTPUT
          echo "command=ci" >> $GITHUB_OUTPUT
          echo "runner=npx --no-install" >> $GITHUB_OUTPUT
          echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "Unable to determine package manager"
          exit 1
        fi

    - run: echo "1${{ steps.detect-package-manager.outputs.manager }}"
    - run: echo "1${{ steps.detect-package-manager.outputs.command }}"
    - run: echo "1${{ steps.detect-package-manager.outputs.runner }}"

    - name: Enable Corepack
      run: corepack enable

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: ${{ steps.detect-package-manager.outputs.manager }}

    - name: Install dependencies
      run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

    - name: Ensure NuxtHub module is installed
      run: npx nuxthub@latest ensure

    - name: Build with Astro
      run: |
        ${{ steps.detect-package-manager.outputs.runner }} astro build

    # - name: Build application
    #   run: npm run build

    - name: Deploy to NuxtHub
      uses: nuxt-hub/action@v1
      id: deploy
      with:
        project-key: fb-landing-kbyn
